---
- hosts: all
  vars_files:
    - vars/dsa-deploy.yml
  tasks:
    - name: Configure the playbook for the current distribution
      include_vars: '{{ item }}'
      with_first_found:
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version|truncate(2) }}.yml"
        - "vars/default.yml"

    - name: Update user
      debug: msg="Selected agent is {{ ansible_distribution }}-{{ ansible_distribution_major_version|truncate(2) }}"

    - name: Update user
      debug: msg="Downloading agent from https://{{ dsm_agent_download_hostname }}:{{ dsm_agent_download_port }}/{{ agent_relative_path }}/{{ ansible_architecture }}/"